version: '3.8'

services:
  #tell to build using dockerfile
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #save the backend files to volume (More later)
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    #all other environment variables taken from .env file
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  #added new service called db and pull down the postgres-13-alpine image
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
# valume assure that our containers cam maintain state between runs
# We wouldn't want to drop our database each time we kill our running container.
volumes:
  postgres_data:
